title: CSP4CMSIS
description: >
  Formal Process Networks for Safe Embedded AI on ARM Silicon.
  <br><br>
  <a href="./api">View API Reference</a> | 
  <a href="./CSP4CMSIS_cheatcheet.pdf">Download Cheatsheet</a>
theme: jekyll-theme-minimal
show_downloads: true

# This ensures the compiler uses the SCSS overrides
remote_theme: pages-themes/minimal@v0.2.0

mathjs: true
